spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root@123

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect