spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mushroominator
    username: mushroom
    password: mushroom123

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/mushroominator
    user: mushroom
    password: mushroom123
    default-schema: mushroominator

rabbitmq:
  host: 192.168.0.204
  port: 5672
  mqttport: 1883
  username: alex

telegram.bot:
  username: mushroominatorbot

#logging.level.org.springframework.web: DEBUG
