spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mushroominator
    username: mushroom
    password: mushroom123

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/mushroominator
    user: mushroom
    password: mushroom123
    default-schema: mushroominator
